name:                           coverage

on:                             [push]

env: 
  CODECOV_TOKEN: 7f09ca79-34d7-4a5a-b6fd-b3b477a7b2e9

jobs:
  test:
    name:                       coverage
    runs-on:                    self-hosted
    container:
      image:                    xd009642/tarpaulin:develop-nightly
      options:                  --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Check if any rust files have changed
        id: rust-files-changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.rs
            Cargo.toml
            Cargo.lock

      - name: Generate code coverage
        if: steps.rust-files-changed.outputs.any_changed == 'true'
        run: |
          cargo +nightly tarpaulin --verbose --workspace --timeout 120 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
